# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_tab_interp', [dirname(__file__)])
        except ImportError:
            import _tab_interp
            return _tab_interp
        if fp is not None:
            try:
                _mod = imp.load_module('_tab_interp', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _tab_interp = swig_import_helper()
    del swig_import_helper
else:
    import _tab_interp
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class coolHeatDust(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, coolHeatDust, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, coolHeatDust, name)
    __repr__ = _swig_repr
    __swig_setmethods__["dCool"] = _tab_interp.coolHeatDust_dCool_set
    __swig_getmethods__["dCool"] = _tab_interp.coolHeatDust_dCool_get
    if _newclass:dCool = _swig_property(_tab_interp.coolHeatDust_dCool_get, _tab_interp.coolHeatDust_dCool_set)
    __swig_setmethods__["dHeat"] = _tab_interp.coolHeatDust_dHeat_set
    __swig_getmethods__["dHeat"] = _tab_interp.coolHeatDust_dHeat_get
    if _newclass:dHeat = _swig_property(_tab_interp.coolHeatDust_dHeat_get, _tab_interp.coolHeatDust_dHeat_set)
    __swig_setmethods__["dustT"] = _tab_interp.coolHeatDust_dustT_set
    __swig_getmethods__["dustT"] = _tab_interp.coolHeatDust_dustT_get
    if _newclass:dustT = _swig_property(_tab_interp.coolHeatDust_dustT_get, _tab_interp.coolHeatDust_dustT_set)
    __swig_setmethods__["opac_abs"] = _tab_interp.coolHeatDust_opac_abs_set
    __swig_getmethods__["opac_abs"] = _tab_interp.coolHeatDust_opac_abs_get
    if _newclass:opac_abs = _swig_property(_tab_interp.coolHeatDust_opac_abs_get, _tab_interp.coolHeatDust_opac_abs_set)
    __swig_setmethods__["opac_scat"] = _tab_interp.coolHeatDust_opac_scat_set
    __swig_getmethods__["opac_scat"] = _tab_interp.coolHeatDust_opac_scat_get
    if _newclass:opac_scat = _swig_property(_tab_interp.coolHeatDust_opac_scat_get, _tab_interp.coolHeatDust_opac_scat_set)
    __swig_setmethods__["dg"] = _tab_interp.coolHeatDust_dg_set
    __swig_getmethods__["dg"] = _tab_interp.coolHeatDust_dg_get
    if _newclass:dg = _swig_property(_tab_interp.coolHeatDust_dg_get, _tab_interp.coolHeatDust_dg_set)
    __swig_setmethods__["column_out"] = _tab_interp.coolHeatDust_column_out_set
    __swig_getmethods__["column_out"] = _tab_interp.coolHeatDust_column_out_get
    if _newclass:column_out = _swig_property(_tab_interp.coolHeatDust_column_out_get, _tab_interp.coolHeatDust_column_out_set)
    __swig_setmethods__["arad"] = _tab_interp.coolHeatDust_arad_set
    __swig_getmethods__["arad"] = _tab_interp.coolHeatDust_arad_get
    if _newclass:arad = _swig_property(_tab_interp.coolHeatDust_arad_get, _tab_interp.coolHeatDust_arad_set)
    __swig_setmethods__["line_co1"] = _tab_interp.coolHeatDust_line_co1_set
    __swig_getmethods__["line_co1"] = _tab_interp.coolHeatDust_line_co1_get
    if _newclass:line_co1 = _swig_property(_tab_interp.coolHeatDust_line_co1_get, _tab_interp.coolHeatDust_line_co1_set)
    __swig_setmethods__["line_co2"] = _tab_interp.coolHeatDust_line_co2_set
    __swig_getmethods__["line_co2"] = _tab_interp.coolHeatDust_line_co2_get
    if _newclass:line_co2 = _swig_property(_tab_interp.coolHeatDust_line_co2_get, _tab_interp.coolHeatDust_line_co2_set)
    __swig_setmethods__["line_hcn1"] = _tab_interp.coolHeatDust_line_hcn1_set
    __swig_getmethods__["line_hcn1"] = _tab_interp.coolHeatDust_line_hcn1_get
    if _newclass:line_hcn1 = _swig_property(_tab_interp.coolHeatDust_line_hcn1_get, _tab_interp.coolHeatDust_line_hcn1_set)
    __swig_setmethods__["line_hcn2"] = _tab_interp.coolHeatDust_line_hcn2_set
    __swig_getmethods__["line_hcn2"] = _tab_interp.coolHeatDust_line_hcn2_get
    if _newclass:line_hcn2 = _swig_property(_tab_interp.coolHeatDust_line_hcn2_get, _tab_interp.coolHeatDust_line_hcn2_set)
    __swig_setmethods__["line_h2_1"] = _tab_interp.coolHeatDust_line_h2_1_set
    __swig_getmethods__["line_h2_1"] = _tab_interp.coolHeatDust_line_h2_1_get
    if _newclass:line_h2_1 = _swig_property(_tab_interp.coolHeatDust_line_h2_1_get, _tab_interp.coolHeatDust_line_h2_1_set)
    __swig_setmethods__["line_h2_2"] = _tab_interp.coolHeatDust_line_h2_2_set
    __swig_getmethods__["line_h2_2"] = _tab_interp.coolHeatDust_line_h2_2_get
    if _newclass:line_h2_2 = _swig_property(_tab_interp.coolHeatDust_line_h2_2_get, _tab_interp.coolHeatDust_line_h2_2_set)
    __swig_setmethods__["line_h2_3"] = _tab_interp.coolHeatDust_line_h2_3_set
    __swig_getmethods__["line_h2_3"] = _tab_interp.coolHeatDust_line_h2_3_get
    if _newclass:line_h2_3 = _swig_property(_tab_interp.coolHeatDust_line_h2_3_get, _tab_interp.coolHeatDust_line_h2_3_set)
    __swig_setmethods__["line_12m"] = _tab_interp.coolHeatDust_line_12m_set
    __swig_getmethods__["line_12m"] = _tab_interp.coolHeatDust_line_12m_get
    if _newclass:line_12m = _swig_property(_tab_interp.coolHeatDust_line_12m_get, _tab_interp.coolHeatDust_line_12m_set)
    __swig_setmethods__["line_8m"] = _tab_interp.coolHeatDust_line_8m_set
    __swig_getmethods__["line_8m"] = _tab_interp.coolHeatDust_line_8m_get
    if _newclass:line_8m = _swig_property(_tab_interp.coolHeatDust_line_8m_get, _tab_interp.coolHeatDust_line_8m_set)
    __swig_setmethods__["line_850m"] = _tab_interp.coolHeatDust_line_850m_set
    __swig_getmethods__["line_850m"] = _tab_interp.coolHeatDust_line_850m_get
    if _newclass:line_850m = _swig_property(_tab_interp.coolHeatDust_line_850m_get, _tab_interp.coolHeatDust_line_850m_set)
    def __init__(self): 
        this = _tab_interp.new_coolHeatDust()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _tab_interp.delete_coolHeatDust
    __del__ = lambda self : None;
coolHeatDust_swigregister = _tab_interp.coolHeatDust_swigregister
coolHeatDust_swigregister(coolHeatDust)

class coolHeatDustArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, coolHeatDustArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, coolHeatDustArray, name)
    __repr__ = _swig_repr
    __swig_setmethods__["dCool"] = _tab_interp.coolHeatDustArray_dCool_set
    __swig_getmethods__["dCool"] = _tab_interp.coolHeatDustArray_dCool_get
    if _newclass:dCool = _swig_property(_tab_interp.coolHeatDustArray_dCool_get, _tab_interp.coolHeatDustArray_dCool_set)
    __swig_setmethods__["dHeat"] = _tab_interp.coolHeatDustArray_dHeat_set
    __swig_getmethods__["dHeat"] = _tab_interp.coolHeatDustArray_dHeat_get
    if _newclass:dHeat = _swig_property(_tab_interp.coolHeatDustArray_dHeat_get, _tab_interp.coolHeatDustArray_dHeat_set)
    __swig_setmethods__["dustT"] = _tab_interp.coolHeatDustArray_dustT_set
    __swig_getmethods__["dustT"] = _tab_interp.coolHeatDustArray_dustT_get
    if _newclass:dustT = _swig_property(_tab_interp.coolHeatDustArray_dustT_get, _tab_interp.coolHeatDustArray_dustT_set)
    __swig_setmethods__["opac_abs"] = _tab_interp.coolHeatDustArray_opac_abs_set
    __swig_getmethods__["opac_abs"] = _tab_interp.coolHeatDustArray_opac_abs_get
    if _newclass:opac_abs = _swig_property(_tab_interp.coolHeatDustArray_opac_abs_get, _tab_interp.coolHeatDustArray_opac_abs_set)
    __swig_setmethods__["opac_scat"] = _tab_interp.coolHeatDustArray_opac_scat_set
    __swig_getmethods__["opac_scat"] = _tab_interp.coolHeatDustArray_opac_scat_get
    if _newclass:opac_scat = _swig_property(_tab_interp.coolHeatDustArray_opac_scat_get, _tab_interp.coolHeatDustArray_opac_scat_set)
    __swig_setmethods__["dg"] = _tab_interp.coolHeatDustArray_dg_set
    __swig_getmethods__["dg"] = _tab_interp.coolHeatDustArray_dg_get
    if _newclass:dg = _swig_property(_tab_interp.coolHeatDustArray_dg_get, _tab_interp.coolHeatDustArray_dg_set)
    __swig_setmethods__["column_out"] = _tab_interp.coolHeatDustArray_column_out_set
    __swig_getmethods__["column_out"] = _tab_interp.coolHeatDustArray_column_out_get
    if _newclass:column_out = _swig_property(_tab_interp.coolHeatDustArray_column_out_get, _tab_interp.coolHeatDustArray_column_out_set)
    __swig_setmethods__["arad"] = _tab_interp.coolHeatDustArray_arad_set
    __swig_getmethods__["arad"] = _tab_interp.coolHeatDustArray_arad_get
    if _newclass:arad = _swig_property(_tab_interp.coolHeatDustArray_arad_get, _tab_interp.coolHeatDustArray_arad_set)
    __swig_setmethods__["line_co1"] = _tab_interp.coolHeatDustArray_line_co1_set
    __swig_getmethods__["line_co1"] = _tab_interp.coolHeatDustArray_line_co1_get
    if _newclass:line_co1 = _swig_property(_tab_interp.coolHeatDustArray_line_co1_get, _tab_interp.coolHeatDustArray_line_co1_set)
    __swig_setmethods__["line_co2"] = _tab_interp.coolHeatDustArray_line_co2_set
    __swig_getmethods__["line_co2"] = _tab_interp.coolHeatDustArray_line_co2_get
    if _newclass:line_co2 = _swig_property(_tab_interp.coolHeatDustArray_line_co2_get, _tab_interp.coolHeatDustArray_line_co2_set)
    __swig_setmethods__["line_hcn1"] = _tab_interp.coolHeatDustArray_line_hcn1_set
    __swig_getmethods__["line_hcn1"] = _tab_interp.coolHeatDustArray_line_hcn1_get
    if _newclass:line_hcn1 = _swig_property(_tab_interp.coolHeatDustArray_line_hcn1_get, _tab_interp.coolHeatDustArray_line_hcn1_set)
    __swig_setmethods__["line_hcn2"] = _tab_interp.coolHeatDustArray_line_hcn2_set
    __swig_getmethods__["line_hcn2"] = _tab_interp.coolHeatDustArray_line_hcn2_get
    if _newclass:line_hcn2 = _swig_property(_tab_interp.coolHeatDustArray_line_hcn2_get, _tab_interp.coolHeatDustArray_line_hcn2_set)
    __swig_setmethods__["line_h2_1"] = _tab_interp.coolHeatDustArray_line_h2_1_set
    __swig_getmethods__["line_h2_1"] = _tab_interp.coolHeatDustArray_line_h2_1_get
    if _newclass:line_h2_1 = _swig_property(_tab_interp.coolHeatDustArray_line_h2_1_get, _tab_interp.coolHeatDustArray_line_h2_1_set)
    __swig_setmethods__["line_h2_2"] = _tab_interp.coolHeatDustArray_line_h2_2_set
    __swig_getmethods__["line_h2_2"] = _tab_interp.coolHeatDustArray_line_h2_2_get
    if _newclass:line_h2_2 = _swig_property(_tab_interp.coolHeatDustArray_line_h2_2_get, _tab_interp.coolHeatDustArray_line_h2_2_set)
    __swig_setmethods__["line_h2_3"] = _tab_interp.coolHeatDustArray_line_h2_3_set
    __swig_getmethods__["line_h2_3"] = _tab_interp.coolHeatDustArray_line_h2_3_get
    if _newclass:line_h2_3 = _swig_property(_tab_interp.coolHeatDustArray_line_h2_3_get, _tab_interp.coolHeatDustArray_line_h2_3_set)
    __swig_setmethods__["line_12mic"] = _tab_interp.coolHeatDustArray_line_12mic_set
    __swig_getmethods__["line_12mic"] = _tab_interp.coolHeatDustArray_line_12mic_get
    if _newclass:line_12mic = _swig_property(_tab_interp.coolHeatDustArray_line_12mic_get, _tab_interp.coolHeatDustArray_line_12mic_set)
    __swig_setmethods__["line_8mic"] = _tab_interp.coolHeatDustArray_line_8mic_set
    __swig_getmethods__["line_8mic"] = _tab_interp.coolHeatDustArray_line_8mic_get
    if _newclass:line_8mic = _swig_property(_tab_interp.coolHeatDustArray_line_8mic_get, _tab_interp.coolHeatDustArray_line_8mic_set)
    __swig_setmethods__["line_850mic"] = _tab_interp.coolHeatDustArray_line_850mic_set
    __swig_getmethods__["line_850mic"] = _tab_interp.coolHeatDustArray_line_850mic_get
    if _newclass:line_850mic = _swig_property(_tab_interp.coolHeatDustArray_line_850mic_get, _tab_interp.coolHeatDustArray_line_850mic_set)
    def __init__(self): 
        this = _tab_interp.new_coolHeatDustArray()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _tab_interp.delete_coolHeatDustArray
    __del__ = lambda self : None;
coolHeatDustArray_swigregister = _tab_interp.coolHeatDustArray_swigregister
coolHeatDustArray_swigregister(coolHeatDustArray)

class AGN_heat_table(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, AGN_heat_table, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, AGN_heat_table, name)
    __repr__ = _swig_repr
    __swig_setmethods__["agn_heat_tab"] = _tab_interp.AGN_heat_table_agn_heat_tab_set
    __swig_getmethods__["agn_heat_tab"] = _tab_interp.AGN_heat_table_agn_heat_tab_get
    if _newclass:agn_heat_tab = _swig_property(_tab_interp.AGN_heat_table_agn_heat_tab_get, _tab_interp.AGN_heat_table_agn_heat_tab_set)
    __swig_setmethods__["agn_cool_tab"] = _tab_interp.AGN_heat_table_agn_cool_tab_set
    __swig_getmethods__["agn_cool_tab"] = _tab_interp.AGN_heat_table_agn_cool_tab_get
    if _newclass:agn_cool_tab = _swig_property(_tab_interp.AGN_heat_table_agn_cool_tab_get, _tab_interp.AGN_heat_table_agn_cool_tab_set)
    __swig_setmethods__["agn_dust_tab"] = _tab_interp.AGN_heat_table_agn_dust_tab_set
    __swig_getmethods__["agn_dust_tab"] = _tab_interp.AGN_heat_table_agn_dust_tab_get
    if _newclass:agn_dust_tab = _swig_property(_tab_interp.AGN_heat_table_agn_dust_tab_get, _tab_interp.AGN_heat_table_agn_dust_tab_set)
    __swig_setmethods__["agn_dg_tab"] = _tab_interp.AGN_heat_table_agn_dg_tab_set
    __swig_getmethods__["agn_dg_tab"] = _tab_interp.AGN_heat_table_agn_dg_tab_get
    if _newclass:agn_dg_tab = _swig_property(_tab_interp.AGN_heat_table_agn_dg_tab_get, _tab_interp.AGN_heat_table_agn_dg_tab_set)
    __swig_setmethods__["agn_opac_scat_tab"] = _tab_interp.AGN_heat_table_agn_opac_scat_tab_set
    __swig_getmethods__["agn_opac_scat_tab"] = _tab_interp.AGN_heat_table_agn_opac_scat_tab_get
    if _newclass:agn_opac_scat_tab = _swig_property(_tab_interp.AGN_heat_table_agn_opac_scat_tab_get, _tab_interp.AGN_heat_table_agn_opac_scat_tab_set)
    __swig_setmethods__["agn_opac_abs_tab"] = _tab_interp.AGN_heat_table_agn_opac_abs_tab_set
    __swig_getmethods__["agn_opac_abs_tab"] = _tab_interp.AGN_heat_table_agn_opac_abs_tab_get
    if _newclass:agn_opac_abs_tab = _swig_property(_tab_interp.AGN_heat_table_agn_opac_abs_tab_get, _tab_interp.AGN_heat_table_agn_opac_abs_tab_set)
    __swig_setmethods__["agn_arad_tab"] = _tab_interp.AGN_heat_table_agn_arad_tab_set
    __swig_getmethods__["agn_arad_tab"] = _tab_interp.AGN_heat_table_agn_arad_tab_get
    if _newclass:agn_arad_tab = _swig_property(_tab_interp.AGN_heat_table_agn_arad_tab_get, _tab_interp.AGN_heat_table_agn_arad_tab_set)
    __swig_setmethods__["agn_line_co1"] = _tab_interp.AGN_heat_table_agn_line_co1_set
    __swig_getmethods__["agn_line_co1"] = _tab_interp.AGN_heat_table_agn_line_co1_get
    if _newclass:agn_line_co1 = _swig_property(_tab_interp.AGN_heat_table_agn_line_co1_get, _tab_interp.AGN_heat_table_agn_line_co1_set)
    __swig_setmethods__["agn_line_co2"] = _tab_interp.AGN_heat_table_agn_line_co2_set
    __swig_getmethods__["agn_line_co2"] = _tab_interp.AGN_heat_table_agn_line_co2_get
    if _newclass:agn_line_co2 = _swig_property(_tab_interp.AGN_heat_table_agn_line_co2_get, _tab_interp.AGN_heat_table_agn_line_co2_set)
    __swig_setmethods__["agn_line_hcn1"] = _tab_interp.AGN_heat_table_agn_line_hcn1_set
    __swig_getmethods__["agn_line_hcn1"] = _tab_interp.AGN_heat_table_agn_line_hcn1_get
    if _newclass:agn_line_hcn1 = _swig_property(_tab_interp.AGN_heat_table_agn_line_hcn1_get, _tab_interp.AGN_heat_table_agn_line_hcn1_set)
    __swig_setmethods__["agn_line_hcn2"] = _tab_interp.AGN_heat_table_agn_line_hcn2_set
    __swig_getmethods__["agn_line_hcn2"] = _tab_interp.AGN_heat_table_agn_line_hcn2_get
    if _newclass:agn_line_hcn2 = _swig_property(_tab_interp.AGN_heat_table_agn_line_hcn2_get, _tab_interp.AGN_heat_table_agn_line_hcn2_set)
    __swig_setmethods__["agn_line_h2_1"] = _tab_interp.AGN_heat_table_agn_line_h2_1_set
    __swig_getmethods__["agn_line_h2_1"] = _tab_interp.AGN_heat_table_agn_line_h2_1_get
    if _newclass:agn_line_h2_1 = _swig_property(_tab_interp.AGN_heat_table_agn_line_h2_1_get, _tab_interp.AGN_heat_table_agn_line_h2_1_set)
    __swig_setmethods__["agn_line_h2_2"] = _tab_interp.AGN_heat_table_agn_line_h2_2_set
    __swig_getmethods__["agn_line_h2_2"] = _tab_interp.AGN_heat_table_agn_line_h2_2_get
    if _newclass:agn_line_h2_2 = _swig_property(_tab_interp.AGN_heat_table_agn_line_h2_2_get, _tab_interp.AGN_heat_table_agn_line_h2_2_set)
    __swig_setmethods__["agn_line_h2_3"] = _tab_interp.AGN_heat_table_agn_line_h2_3_set
    __swig_getmethods__["agn_line_h2_3"] = _tab_interp.AGN_heat_table_agn_line_h2_3_get
    if _newclass:agn_line_h2_3 = _swig_property(_tab_interp.AGN_heat_table_agn_line_h2_3_get, _tab_interp.AGN_heat_table_agn_line_h2_3_set)
    __swig_setmethods__["agn_line_12m"] = _tab_interp.AGN_heat_table_agn_line_12m_set
    __swig_getmethods__["agn_line_12m"] = _tab_interp.AGN_heat_table_agn_line_12m_get
    if _newclass:agn_line_12m = _swig_property(_tab_interp.AGN_heat_table_agn_line_12m_get, _tab_interp.AGN_heat_table_agn_line_12m_set)
    __swig_setmethods__["agn_line_8m"] = _tab_interp.AGN_heat_table_agn_line_8m_set
    __swig_getmethods__["agn_line_8m"] = _tab_interp.AGN_heat_table_agn_line_8m_get
    if _newclass:agn_line_8m = _swig_property(_tab_interp.AGN_heat_table_agn_line_8m_get, _tab_interp.AGN_heat_table_agn_line_8m_set)
    __swig_setmethods__["agn_line_850m"] = _tab_interp.AGN_heat_table_agn_line_850m_set
    __swig_getmethods__["agn_line_850m"] = _tab_interp.AGN_heat_table_agn_line_850m_get
    if _newclass:agn_line_850m = _swig_property(_tab_interp.AGN_heat_table_agn_line_850m_get, _tab_interp.AGN_heat_table_agn_line_850m_set)
    __swig_setmethods__["agn_column_out_tab"] = _tab_interp.AGN_heat_table_agn_column_out_tab_set
    __swig_getmethods__["agn_column_out_tab"] = _tab_interp.AGN_heat_table_agn_column_out_tab_get
    if _newclass:agn_column_out_tab = _swig_property(_tab_interp.AGN_heat_table_agn_column_out_tab_get, _tab_interp.AGN_heat_table_agn_column_out_tab_set)
    __swig_setmethods__["tables"] = _tab_interp.AGN_heat_table_tables_set
    __swig_getmethods__["tables"] = _tab_interp.AGN_heat_table_tables_get
    if _newclass:tables = _swig_property(_tab_interp.AGN_heat_table_tables_get, _tab_interp.AGN_heat_table_tables_set)
    __swig_setmethods__["ntabs"] = _tab_interp.AGN_heat_table_ntabs_set
    __swig_getmethods__["ntabs"] = _tab_interp.AGN_heat_table_ntabs_get
    if _newclass:ntabs = _swig_property(_tab_interp.AGN_heat_table_ntabs_get, _tab_interp.AGN_heat_table_ntabs_set)
    __swig_setmethods__["lineArrays"] = _tab_interp.AGN_heat_table_lineArrays_set
    __swig_getmethods__["lineArrays"] = _tab_interp.AGN_heat_table_lineArrays_get
    if _newclass:lineArrays = _swig_property(_tab_interp.AGN_heat_table_lineArrays_get, _tab_interp.AGN_heat_table_lineArrays_set)
    __swig_setmethods__["agn_ntemp"] = _tab_interp.AGN_heat_table_agn_ntemp_set
    __swig_getmethods__["agn_ntemp"] = _tab_interp.AGN_heat_table_agn_ntemp_get
    if _newclass:agn_ntemp = _swig_property(_tab_interp.AGN_heat_table_agn_ntemp_get, _tab_interp.AGN_heat_table_agn_ntemp_set)
    __swig_setmethods__["agn_ndense"] = _tab_interp.AGN_heat_table_agn_ndense_set
    __swig_getmethods__["agn_ndense"] = _tab_interp.AGN_heat_table_agn_ndense_get
    if _newclass:agn_ndense = _swig_property(_tab_interp.AGN_heat_table_agn_ndense_get, _tab_interp.AGN_heat_table_agn_ndense_set)
    __swig_setmethods__["agn_nintensity"] = _tab_interp.AGN_heat_table_agn_nintensity_set
    __swig_getmethods__["agn_nintensity"] = _tab_interp.AGN_heat_table_agn_nintensity_get
    if _newclass:agn_nintensity = _swig_property(_tab_interp.AGN_heat_table_agn_nintensity_get, _tab_interp.AGN_heat_table_agn_nintensity_set)
    __swig_setmethods__["agn_ncolumn_in"] = _tab_interp.AGN_heat_table_agn_ncolumn_in_set
    __swig_getmethods__["agn_ncolumn_in"] = _tab_interp.AGN_heat_table_agn_ncolumn_in_get
    if _newclass:agn_ncolumn_in = _swig_property(_tab_interp.AGN_heat_table_agn_ncolumn_in_get, _tab_interp.AGN_heat_table_agn_ncolumn_in_set)
    __swig_setmethods__["agn_temp_vals"] = _tab_interp.AGN_heat_table_agn_temp_vals_set
    __swig_getmethods__["agn_temp_vals"] = _tab_interp.AGN_heat_table_agn_temp_vals_get
    if _newclass:agn_temp_vals = _swig_property(_tab_interp.AGN_heat_table_agn_temp_vals_get, _tab_interp.AGN_heat_table_agn_temp_vals_set)
    __swig_setmethods__["agn_dense_vals"] = _tab_interp.AGN_heat_table_agn_dense_vals_set
    __swig_getmethods__["agn_dense_vals"] = _tab_interp.AGN_heat_table_agn_dense_vals_get
    if _newclass:agn_dense_vals = _swig_property(_tab_interp.AGN_heat_table_agn_dense_vals_get, _tab_interp.AGN_heat_table_agn_dense_vals_set)
    __swig_setmethods__["agn_intensity_vals"] = _tab_interp.AGN_heat_table_agn_intensity_vals_set
    __swig_getmethods__["agn_intensity_vals"] = _tab_interp.AGN_heat_table_agn_intensity_vals_get
    if _newclass:agn_intensity_vals = _swig_property(_tab_interp.AGN_heat_table_agn_intensity_vals_get, _tab_interp.AGN_heat_table_agn_intensity_vals_set)
    __swig_setmethods__["agn_column_in_vals"] = _tab_interp.AGN_heat_table_agn_column_in_vals_set
    __swig_getmethods__["agn_column_in_vals"] = _tab_interp.AGN_heat_table_agn_column_in_vals_get
    if _newclass:agn_column_in_vals = _swig_property(_tab_interp.AGN_heat_table_agn_column_in_vals_get, _tab_interp.AGN_heat_table_agn_column_in_vals_set)
    def setupTable(self, *args): return _tab_interp.AGN_heat_table_setupTable(self, *args)
    def agn_tab_index(self, *args): return _tab_interp.AGN_heat_table_agn_tab_index(self, *args)
    def __init__(self): 
        this = _tab_interp.new_AGN_heat_table()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _tab_interp.delete_AGN_heat_table
    __del__ = lambda self : None;
AGN_heat_table_swigregister = _tab_interp.AGN_heat_table_swigregister
AGN_heat_table_swigregister(AGN_heat_table)

class CoolHeatTab(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CoolHeatTab, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CoolHeatTab, name)
    __repr__ = _swig_repr
    def interpTab(self, *args): return _tab_interp.CoolHeatTab_interpTab(self, *args)
    def interpTabArray(self, *args): return _tab_interp.CoolHeatTab_interpTabArray(self, *args)
    def __init__(self, *args): 
        this = _tab_interp.new_CoolHeatTab(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _tab_interp.delete_CoolHeatTab
    __del__ = lambda self : None;
CoolHeatTab_swigregister = _tab_interp.CoolHeatTab_swigregister
CoolHeatTab_swigregister(CoolHeatTab)

# This file is compatible with both classic and new-style classes.


