for i in longrun_medflow_settled_defaultaniso_polar longrun_medflow_vesc_defaultaniso longrun_medflow_vesc_defaultaniso_polar longrun_weakflow_rapid_defaultaniso longrun_weakflow_rapid_defaultaniso_polar longrun_weakflow_settled_defaultaniso longrun_weakflow_settled_defaultaniso_polar longrun_weakflow_vesc_defaultaniso longrun_weakflow_vesc_defaultaniso_polar newflow_settled_thin_up newflow_vesc_thin_45 newflow_vesc_thin_side newflow_vesc_thin_up
do
    ./angle_views.sh $i
done